---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
  - name: update apt cache
    apt:
      cache_valid_time: 600
  roles:
    - role: ansible-homebridge
  vars:
    homebridge_plugins:
      - name: homebridge-dummy
        version: 0.3.0
    homebridge_accessories:
      - accessory: "DummySwitch"
        name: "My Switch 1"
    homebridge_enable_cap_net_raw: true
