---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint
platforms:
  - name: ansible-homebridge
    image: minimum2scp/systemd-stretch:latest
    cap_add:
      - SYS_ADMIN
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
